### ISSUE TITLE
When a new model is download, we do require an addition selection to switch to that language pair

### ISSUE THREAD

**Issue by XapaJIaMnu** [XapaJIaMnu/translateLocally#18]
@jelmervdl this would need to be fixed. I'll do it as I refactor the model selection.

**Comment by jelmervdl** [comment]
In `MainWindow::handleDownload()`, adding a call to `MarianInterface::resetModel` after `models_.writeModel(...)` should do the trick. Maybe `writeModel` should return whether or not it was successful, so you don't call resetModel on a model that never got extracted correctly.

**Comment by jelmervdl** [comment]
I quickly tried to see whether it was really as simple as I imagined. it wasn't, I forgot that you would also need to select the newly downloaded model in the model dropdown. And since you're refactoring that part anyway, I wasn't planning on merging this. Still, in case it may be of any use to you: https://github.com/jelmervdl/translateLocally/tree/select-downloaded-model

**Comment by XapaJIaMnu** [comment]
I will fix it when I finish the refactoring, don't worry about it for now.
