### ISSUE TITLE
Big chunks of texts get translated twice.

### ISSUE THREAD

**Issue by XapaJIaMnu** [XapaJIaMnu/translateLocally#31]
If you copy paste a large chunk of text, eg https://en.wikipedia.org/wiki/Spanish_Inquisition into the translation window, the translation happens twice. Not sure if it's the full text twice, or a  section of the full text and then the full text.

This is more obvious when using the speed  indicator: https://github.com/XapaJIaMnu/translateLocally/pull/29

@jelmervdl ideas?

**Comment by jelmervdl** [comment]
I think I know why. The translate-as-you-type submits twice: once after each keypress, and once after you stopped typing (or 200ms after the last keypress unless that timer was reset by another keypress)

The first submission is of all complete words (so effectively all words up to the last space). It also checks whether that input has change since last submission. The idea was that it would translate every time you finished typing a word. (It does only work if you're typing at the end of the sentence, and if your language has spaces, so all in all not a very robust heuristic.)

The second submission is the timeout. In case you just typed a single word, or (more realistically) you didn't type a space after the last word in your sentence. This submission will always be the full text.

I'm thinking that just getting rid of the first submission would be a good idea. The timeout on the second submission could give the impression nothing is happening while you type (if you type fast enough) but if that's annoying we could make the timeout smaller. With the way `MarianInterface` now works, there is no real cost of submitting new text to translate often.
