### ISSUE TITLE
Handle updating outdated models better.

### ISSUE THREAD

**Issue by XapaJIaMnu** [XapaJIaMnu/translateLocally#35]
Currently we have a rudimentary support for updating outdated models that the user has stored locally. The approach has two major shortcomings:

1) When we update the model, we don't remove the old outdated entry from the drop down menu (both entries will point to the same, new model)
2) We do not switch/reload to the updated model right away.

**Comment by XapaJIaMnu** [comment]
Is 2) Fixed? Now that we removed the stderr I'm not really sure xD

**Comment by jelmervdl** [comment]
I assumed so because the path would be the same for newly downloaded models and updated models. But I assumed wrong, since the model change happens through the Setting that emits a valueChanged. Problem was, Setting was being a bit too smart about not emitting when the value actually stayed the same. So I added a switch to trigger always emitting.

Tested it by removing `--quiet`, and yep, model now reloads when updated.
