### ISSUE TITLE
Delete the tar.gz once downloaded and extracted

### ISSUE THREAD

**Issue by XapaJIaMnu** [XapaJIaMnu/translateLocally#36]
Once a model has been downlaoded and extracted, we should delete the .tar.gz, as it is not used anymore.

**Comment by jelmervdl** [comment]
This requires some changes to `ModelManager::extractTarGz` to return (or throw) whether it was successful or not. Other than that I see no complications in deleting the tar.gz. once extractTarGz is done.

That function needs some refactoring anyway. There's some cli leftovers in that function, failure does not stop extraction, and there's some error message formatting going on that doesn't work with the signal/slots system it's hooked into.

I won't mind spending some time on this tomorrow. I'd also like to look into whether extracting can be moved off the main thread and what happens when the user clicks "cancel" during extraction.

**Comment by XapaJIaMnu** [comment]
Yeah, sorry about that, that was completely my bad. I coded this very hastily for the MVP. Go for it.

**Comment by jelmervdl** [comment]
I've reworked the downloading & extracting part a bit in 7e7cbe6...7674e6e to download to a temporary file and extract it. The file as the same lifetime as the network reply object itself, so it gets deleted both in case of success as well as failure.
