### ISSUE TITLE
Equal size vsplit windows for source and target

### ISSUE THREAD

**Issue by jerinphilip** [XapaJIaMnu/translateLocally#4]
Feature request:

![image](https://user-images.githubusercontent.com/727292/115758446-08ebea80-a397-11eb-9ab9-cfab95c5dd13.png)

Can I have an equal size vsplit windows for source and target text?

Wishful thinking - synchronized scrolling.

**Comment by XapaJIaMnu** [comment]
You can't have equal size. What you want to have is adjustable size. Which is on the TODO

**Comment by jerinphilip** [comment]
> You can't have equal size.

Confused here, Why? I want only one control that adjusts size, and adjusts size of both by the same value scale-x, scale-y on x, y. Both should be scrollable in overflow of text (and ideally sync-scrollable). 

vsplit to check source and translation side by side.

**Comment by XapaJIaMnu** [comment]
ok, let me be more explicit. This would be so far down the priorities that I don't want to consider it a potential feature for now.

Why? Too many options. You want locked scrolling? Sure, but maybe some users don't want that. You want the window sizes synchronised? Most people don't really want to waste that much screen real estate on the input as they don't really care about it, especially if it's a language they can't even read (eg Chinese). Adding all these options in an intuitive and unobstructive way  so that it doesn't clutter the GUI would take quite a bit of time.

Potentially in the future, you could use the attention mechanism to highlight words from the two interfaces, auto scroll and so on, but for now I think if I make the size of the fields adjustable, it would solve 99% of the use cases.

Maybe side-by-side arangment like google translate is a good idea, even if I personally don't like it, as I don't often care about the input.

**Comment by jelmervdl** [comment]
Currently we have a (resizable) vertical split. Adding a toggle to the menu to change this to a horizontal split would be quite easy I presume. (but then we should also save the window size in the settings so that people who toggle it to horizontal don't have to resize the window every time) Is that something we would like?

Synced scrolling: implementing it in a naive way is not difficult, but could be pretty annoying for users when it doesn't work. Should be a toggle in the menu. I'm tempted to add this only when the text field is more aware of sentences, and then have both fields optionally scroll both source and target sentences to be visible instead of relative scroll position.

**Comment by jerinphilip** [comment]
> Synced scrolling: implementing it in a naive way is not difficult, but could be pretty annoying for users when it doesn't work. Should be a toggle in the menu.

Response is aware of which source-sentence maps to which target sentence. Unsure if you can use this to your advantage to adjust both like how overleaf does between PDF / source if you get what I mean. That would be nicest IMO. Sync-scroll is at best a hack.

**Comment by jelmervdl** [comment]
Overleaf is a good example of how I imagined it should work, thanks!

**Comment by XapaJIaMnu** [comment]
Fixed by #28
